### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by schleising** [schleising/opensky_downloader#1]
- [x] Download OpenSky data
- [x] Create model for OpenSky data
- [x] Store data in MongoDB
